import os
import json
from pydantic import BaseModel, Field
from google.genai import types
from google.genai.types import SafetySetting, HarmCategory, HarmBlockThreshold
from google.adk.agents import Agent
from google.adk.agents.callback_context import CallbackContext

# ----------------------------------------------------------------------
# 1. Define structured output schema for the evaluator
# ----------------------------------------------------------------------

class EvaluationResult(BaseModel):
    """The structured result of the LLM-as-a-judge evaluation."""
    score: float = Field(
        description="Overall score between 0.0 and 1.0. Itineraries must score 0.8 or higher to pass."
    )
    feasibility_rating: float = Field(
        description="Rating from 0.0 to 1.0 evaluating if flights, accommodations, and activities align chronologically and logically."
    )
    quality_rating: float = Field(
        description="Rating from 0.0 to 1.0 for details, completeness, descriptions, and premium presentation of the itinerary."
    )
    constraint_adherence: float = Field(
        description="Rating from 0.0 to 1.0 for staying within the user's budget and satisfying all requested preferences."
    )
    feedback: str = Field(
        description="Constructive and specific feedback indicating exactly what to improve, what is unrealistic, or why the budget was violated. If score >= 0.8, keep this positive or suggest micro-enhancements."
    )
    passed: bool = Field(
        description="True if score is >= 0.8, False otherwise."
    )

# ----------------------------------------------------------------------
# 2. Define Evaluator Prompt & Instructions
# ----------------------------------------------------------------------

EVALUATOR_INSTRUCTION = (
    "You are an expert quality assurance travel agent acting as an LLM-as-a-Judge.\n"
    "Your job is to objectively evaluate the travel itinerary proposals generated by our primary travel agent.\n\n"
    
    "CRITICAL EVALUATION CRITERIA:\n"
    "1. FEASIBILITY (0.0 to 1.0):\n"
    "   - Do the dates and times connect logically? (e.g., cannot check in to a hotel before the inbound flight lands, cannot have activities before arriving at the destination).\n"
    "   - Are the travel schedules physically realistic?\n"
    "2. QUALITY (0.0 to 1.0):\n"
    "   - Is the summary engaging and premium?\n"
    "   - Are the day-by-day activities detailed with times, titles, locations, and descriptions?\n"
    "   - Ensure there are no placeholder texts, hallucinations, or ungrounded details.\n"
    "3. CONSTRAINT ADHERENCE (0.0 to 1.0):\n"
    "   - Does the total estimated cost stay within the user's budget?\n"
    "   - Were specific request preferences (e.g., museums, seafood, historic walks) incorporated?\n"
    "   - Note: If the primary agent requests a fallback (fallback_requested is True), but provides a highly helpful explanation of why the constraints were impossible and gives recommendations, award a score of 1.0 as the fallback pathway is valid and accurate.\n\n"
    
    "SCORING RULES:\n"
    "- To calculate `score`, take the average of feasibility, quality, and constraint adherence.\n"
    "- Set `passed` to True if and only if `score` is 0.8 or higher.\n"
    "- If `passed` is False, `feedback` must be highly specific, describing exactly which parts are missing, inconsistent, or over budget, so the primary agent knows exactly how to refine the itinerary in the next turn.\n\n"
    
    "Evaluate the following itinerary proposal:\n"
    "User Preferences / Query: {user_query}\n\n"
    "Generated Itinerary Proposal (JSON):\n{itinerary_proposal_json}\n"
)

# ----------------------------------------------------------------------
# 3. Configure safety settings
# ----------------------------------------------------------------------

safety_settings = [
    SafetySetting(
        category=HarmCategory.HARM_CATEGORY_HATE_SPEECH,
        threshold=HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
    ),
    SafetySetting(
        category=HarmCategory.HARM_CATEGORY_HARASSMENT,
        threshold=HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
    ),
    SafetySetting(
        category=HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT,
        threshold=HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
    ),
    SafetySetting(
        category=HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
        threshold=HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
    ),
]

content_config = types.GenerateContentConfig(
    safety_settings=safety_settings,
    temperature=0.1, # Extremely low temperature for objective, deterministic evaluations
)

# ----------------------------------------------------------------------
# 4. Initialize the Evaluator Agent
# ----------------------------------------------------------------------

async def prepare_eval_state(callback_context: CallbackContext) -> None:
    # Default user_query if not already present
    if "user_query" not in callback_context.state:
        query = ""
        for event in callback_context.session.events:
            if event.content and event.content.parts:
                for part in event.content.parts:
                    if part.text:
                        query = part.text
                        break
            if query:
                break
        callback_context.state["user_query"] = query
    
    # Serialize the latest itinerary_proposal dictionary to JSON string
    proposal = callback_context.state.get("itinerary_proposal", {})
    callback_context.state["itinerary_proposal_json"] = json.dumps(proposal, indent=2)

evaluator_agent = Agent(
    name="evaluator_agent",
    model="gemini-3.5-flash", # Highly efficient flash model suited for fast evaluations and structured outputs
    instruction=EVALUATOR_INSTRUCTION,
    output_schema=EvaluationResult,
    output_key="evaluation_result",
    before_agent_callback=prepare_eval_state,
    generate_content_config=content_config,
)
